export const exchangeValue = [
  {
    id: "1",
    CoinTitle: "PITCOIN",
    CoinSubTitle: "PTC",
    value: "49,487",
    valuePercentage: +0.005,
  },
  {
    id: "2",
    CoinTitle: "PITCOIN",
    CoinSubTitle: "PTC",
    value: "49,487",
    valuePercentage: +0.005,
  },
  {
    id: "3",
    CoinTitle: "PITCOIN",
    CoinSubTitle: "PTC",
    value: "49,487",
    valuePercentage: +0.005,
  },
  {
    id: "4",
    CoinTitle: "PITCOIN",
    CoinSubTitle: "PTC",
    value: "49,487",
    valuePercentage: +0.005,
  },
  {
    id: "5",
    CoinTitle: "PITCOIN",
    CoinSubTitle: "PTC",
    value: "49,487",
    valuePercentage: +0.005,
  },
  {
    id: "6",
    CoinTitle: "PITCOIN",
    CoinSubTitle: "PTC",
    value: "49,487",
    valuePercentage: +0.005,
  },
  {
    id: "7",
    CoinTitle: "PITCOIN",
    CoinSubTitle: "PTC",
    value: "49,487",
    valuePercentage: +0.005,
  },
  {
    id: "8",
    CoinTitle: "PITCOIN",
    CoinSubTitle: "PTC",
    value: "49,487",
    valuePercentage: +0.005,
  },
  {
    id: "9",
    CoinTitle: "PITCOIN",
    CoinSubTitle: "PTC",
    value: "49,487",
    valuePercentage: +0.005,
  },
];
