export const mainLinkItem = [
  {
    id: "1",
    url: "/",
    icon: "/icon_box.svg",
    title: "코인지갑",
    subtitle: "Wallet",
  },
  {
    id: "2",
    url: "/",
    icon: "/icon_timer.svg",
    title: "스테이킹",
    subtitle: "Staking",
  },
  {
    id: "3",
    url: "/",
    icon: "/icon_dollar.svg",
    title: "P2P거래소",
    subtitle: "Exchange",
  },
  {
    id: "4",
    url: "/",
    icon: "/icon_box.svg",
    title: "코인지갑",
    subtitle: "Wallet",
  },
];

export const ExchangeCoinList = [
  {
    id: "1",
    url: "/exchange/coin",
    icon: "/P_Coin_icon.png",
    name: "PITCOIN",
    subname: "PTC",
    value: "49,487",
    percentage: "+0.00%",
  },
  {
    id: "2",
    url: "/exchange/coin",
    icon: "/Eth_Coin_icon.png",
    name: "PITCOIN",
    subname: "PTC",
    value: "49,487",
    percentage: "+0.00%",
  },
  {
    id: "3",
    url: "/exchange/coin",
    icon: "/T_Coin_icon.png",
    name: "PITCOIN",
    subname: "PTC",
    value: "49,487",
    percentage: "+0.00%",
  },
  {
    id: "4",
    url: "/exchange/coin",
    icon: "/D_Coin_icon.png",
    name: "PITCOIN",
    subname: "PTC",
    value: "49,487",
    percentage: "+0.00%",
  },
  {
    id: "5",
    url: "/exchange/coin",
    icon: "/R_Coin_icon.png",
    name: "PITCOIN",
    subname: "PTC",
    value: "49,487",
    percentage: "+0.00%",
  },
  {
    id: "6",
    url: "/exchange/coin",
    icon: "/P_Coin_icon.png",
    name: "PITCOIN",
    subname: "PTC",
    value: "49,487",
    percentage: "+0.00%",
  },
  {
    id: "7",
    url: "/exchange/coin",
    icon: "/L_Coin_icon.png",
    name: "PITCOIN",
    subname: "PTC",
    value: "49,487",
    percentage: "+0.00%",
  },
];
